# Common environment variables
x-environment: &common-env
  # key
  MEILI_MASTER_KEY: mykey

services:
  # Meilisearch search engine service
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment: *common-env
    volumes:
      - meili_data:/meili_data

  # DocBase knowledge sync system
  docbase:
    depends_on:
      - meilisearch
    image: gonorth/docbase:latest
    environment:
      <<: *common-env
      MEILI_URL: http://meilisearch:7700
    volumes:
      - data:/data
    ports:
      - "3000:3000"

volumes:
  data:
  meili_data:
